//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.GenericUAServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingsData
    {
        public Nullable<bool> BoolFieldName6 { get; set; }
        public string StringFieldName6 { get; set; }
        public string ByteFieldName6 { get; set; }
        public string ByteStringFieldName6 { get; set; }
        public Nullable<System.DateTime> DateTimeFieldName6 { get; set; }
        public Nullable<double> DoubleFieldName6 { get; set; }
        public Nullable<bool> BoolFieldName5 { get; set; }
        public string StringFieldName5 { get; set; }
        public string ByteFieldName5 { get; set; }
        public string ByteStringFieldName5 { get; set; }
        public Nullable<System.DateTime> DateTimeFieldName5 { get; set; }
        public Nullable<double> DoubleFieldName5 { get; set; }
        public Nullable<bool> BoolFieldName4 { get; set; }
        public string StringFieldName4 { get; set; }
        public string ByteFieldName4 { get; set; }
        public string ByteStringFieldName4 { get; set; }
        public Nullable<System.DateTime> DateTimeFieldName4 { get; set; }
        public Nullable<double> DoubleFieldName4 { get; set; }
        public Nullable<bool> BoolFieldName3 { get; set; }
        public string StringFieldName3 { get; set; }
        public string ByteFieldName3 { get; set; }
        public string ByteStringFieldName3 { get; set; }
        public Nullable<System.DateTime> DateTimeFieldName3 { get; set; }
        public Nullable<double> DoubleFieldName3 { get; set; }
        public Nullable<bool> BoolFieldName2 { get; set; }
        public string StringFieldName2 { get; set; }
        public string ByteFieldName2 { get; set; }
        public string ByteStringFieldName2 { get; set; }
        public Nullable<System.DateTime> DateTimeFieldName2 { get; set; }
        public Nullable<double> DoubleFieldName2 { get; set; }
        public Nullable<bool> BoolFieldName1 { get; set; }
        public string StringFieldName1 { get; set; }
        public string ByteFieldName1 { get; set; }
        public string ByteStringFieldName1 { get; set; }
        public Nullable<System.DateTime> DateTimeFieldName1 { get; set; }
        public Nullable<double> DoubleFieldName1 { get; set; }
        public int id { get; set; }
        public string idProcess { get; set; }
        public Nullable<System.DateTime> processStartDate { get; set; }
    }
}
