CREATE TABLE [dbo].[ReadingsData] (
    [BoolFieldName6]       BIT           NULL,
    [StringFieldName6]     VARCHAR (200) NULL,
    [ByteFieldName6]       VARCHAR (10)  NULL,
    [ByteStringFieldName6] VARCHAR (200) NULL,
    [DateTimeFieldName6]   DATETIME      NULL,
    [DoubleFieldName6]     FLOAT (53)    NULL,
    [BoolFieldName5]       BIT           NULL,
    [StringFieldName5]     VARCHAR (200) NULL,
    [ByteFieldName5]       VARCHAR (10)  NULL,
    [ByteStringFieldName5] VARCHAR (200) NULL,
    [DateTimeFieldName5]   DATETIME      NULL,
    [DoubleFieldName5]     FLOAT (53)    NULL,
    [BoolFieldName4]       BIT           NULL,
    [StringFieldName4]     VARCHAR (200) NULL,
    [ByteFieldName4]       VARCHAR (10)  NULL,
    [ByteStringFieldName4] VARCHAR (200) NULL,
    [DateTimeFieldName4]   DATETIME      NULL,
    [DoubleFieldName4]     FLOAT (53)    NULL,
    [BoolFieldName3]       BIT           NULL,
    [StringFieldName3]     VARCHAR (200) NULL,
    [ByteFieldName3]       VARCHAR (10)  NULL,
    [ByteStringFieldName3] VARCHAR (200) NULL,
    [DateTimeFieldName3]   DATETIME      NULL,
    [DoubleFieldName3]     FLOAT (53)    NULL,
    [BoolFieldName2]       BIT           NULL,
    [StringFieldName2]     VARCHAR (200) NULL,
    [ByteFieldName2]       VARCHAR (10)  NULL,
    [ByteStringFieldName2] VARCHAR (200) NULL,
    [DateTimeFieldName2]   DATETIME      NULL,
    [DoubleFieldName2]     FLOAT (53)    NULL,
    [BoolFieldName1]       BIT           NULL,
    [StringFieldName1]     VARCHAR (200) NULL,
    [ByteFieldName1]       VARCHAR (10)  NULL,
    [ByteStringFieldName1] VARCHAR (200) NULL,
    [DateTimeFieldName1]   DATETIME      NULL,
    [DoubleFieldName1]     FLOAT (53)    NULL,
    [id]                   INT           IDENTITY (1, 1) NOT NULL,
    [idProcess]            NVARCHAR (50) NULL,
    [processStartDate]     DATETIME      CONSTRAINT [DF_ReadingsData_processStartDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [ReadingsData_PK] PRIMARY KEY CLUSTERED ([id] ASC)
);

